# Generated by Django 5.0.4 on 2024-04-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordonnees_GPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cust_Code', models.CharField(max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Declenchement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cust_Code', models.CharField(max_length=20)),
                ('TYPE_DECLEN', models.CharField(max_length=10)),
                ('DATE', models.DateField()),
                ('H_RECEPT', models.TimeField()),
                ('H_DESPATCH', models.TimeField()),
                ('H_ARRIVEE', models.TimeField()),
                ('CODE', models.CharField(max_length=150)),
                ('EQUIPAGE', models.CharField(max_length=150)),
                ('NOM_CLIENT', models.CharField(max_length=200)),
                ('ADRESSE_CLIENT', models.CharField(max_length=200)),
                ('COMMENTAIRE', models.CharField(max_length=500)),
                ('TEMPS_INTER', models.TimeField()),
                ('TEMPS_PATRL', models.TimeField()),
                ('TEMPS_PRONTO', models.TimeField()),
            ],
        ),
    ]
