# Generated by Django 5.0.4 on 2024-04-04 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carte', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coordonnees_GPS',
            new_name='Coordonnee',
        ),
    ]
