# Generated by Django 5.0.4 on 2024-04-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carte', '0002_rename_coordonnees_gps_coordonnee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatch_Engin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vehicule', models.CharField(max_length=30)),
                ('Area', models.CharField(max_length=30)),
                ('Description', models.CharField(max_length=200)),
            ],
        ),
    ]
