# Generated by Django 5.0.4 on 2024-04-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carte', '0003_dispatch_engin'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordonnee',
            name='Adresse',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='coordonnee',
            name='Nom',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
