# Generated by Django 5.0.4 on 2024-04-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carte', '0006_alter_declenchement_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordonnee',
            name='Adresse',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='coordonnee',
            name='Nom',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='declenchement',
            name='ADRESSE_CLIENT',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='declenchement',
            name='CODE',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='declenchement',
            name='COMMENTAIRE',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='declenchement',
            name='EQUIPAGE',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='declenchement',
            name='NOM_CLIENT',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dispatch_engin',
            name='Area',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dispatch_engin',
            name='Description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dispatch_engin',
            name='Vehicule',
            field=models.TextField(),
        ),
    ]
