# Generated by Django 5.0.4 on 2024-04-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carte', '0008_alter_declenchement_adresse_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declenchement',
            name='ADRESSE_CLIENT',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='declenchement',
            name='CODE',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='declenchement',
            name='COMMENTAIRE',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='declenchement',
            name='EQUIPAGE',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='declenchement',
            name='H_ARRIVEE',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='declenchement',
            name='H_DESPATCH',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='declenchement',
            name='TEMPS_INTER',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='declenchement',
            name='TEMPS_PATRL',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='declenchement',
            name='TEMPS_PRONTO',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
